baseURL = "https://www.git-for-kids.de/"
languageCode = "en-us"
title = "Git For Kids - Learn to Learn to Learn Git"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "moon"
